#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.5 on Sun Sep 29 16:49:08 2024
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class TypingMaster(wx.Frame):
	def __init__(self, *args, **kwds):
		# begin wxGlade: TypingMaster.__init__
		kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
		wx.Frame.__init__(self, *args, **kwds)
		self.SetSize((800, 680))
		self.SetTitle(u"DK-打字通")

		# Menu Bar
		self.frame_menubar = wx.MenuBar()
		wxglade_tmp_menu = wx.Menu()
		wxglade_tmp_menu_sub = wx.Menu()
		item = wxglade_tmp_menu_sub.Append(wx.ID_ANY, u"微信二维码", "")
		self.Bind(wx.EVT_MENU, self.OnWechat, item)
		item = wxglade_tmp_menu_sub.Append(wx.ID_ANY, u"支付宝二维码", "")
		self.Bind(wx.EVT_MENU, self.OnAlipay, item)
		wxglade_tmp_menu.Append(wx.ID_ANY, u"赞赏作者", wxglade_tmp_menu_sub, "")
		wxglade_tmp_menu_sub = wx.Menu()
		item = wxglade_tmp_menu_sub.Append(wx.ID_ANY, u"复制群号", "")
		self.Bind(wx.EVT_MENU, self.OnQQGroupNumber, item)
		item = wxglade_tmp_menu_sub.Append(wx.ID_ANY, u"加群二维码", "")
		self.Bind(wx.EVT_MENU, self.OnQQQRCode, item)
		item = wxglade_tmp_menu_sub.Append(wx.ID_ANY, u"跳转链接", "")
		self.Bind(wx.EVT_MENU, self.OnQQLink, item)
		wxglade_tmp_menu.Append(wx.ID_ANY, u"加入QQ群", wxglade_tmp_menu_sub, "")
		item = wxglade_tmp_menu.Append(wx.ID_ANY, u"退出(&X)\tCtrl+X", "")
		self.Bind(wx.EVT_MENU, self.OnExit, item)
		self.frame_menubar.Append(wxglade_tmp_menu, u"文件(&F)")
		wxglade_tmp_menu = wx.Menu()
		item = wxglade_tmp_menu.Append(wx.ID_ANY, u"极限测速(&E)\tCtrl+E", "")
		self.Bind(wx.EVT_MENU, self.OnExtremeSpeed, item)
		item = wxglade_tmp_menu.Append(wx.ID_ANY, u"查看统计(&R)\tCtrl+R", "")
		self.Bind(wx.EVT_MENU, self.OnStatisticReport, item)
		wxglade_tmp_menu_sub = wx.Menu()
		self.frame_menubar.explain_on = wxglade_tmp_menu_sub.Append(wx.ID_ANY, u"开\tCtrl+J", "", wx.ITEM_RADIO)
		self.Bind(wx.EVT_MENU, self.OnWordExplain, self.frame_menubar.explain_on)
		self.frame_menubar.explain_off = wxglade_tmp_menu_sub.Append(wx.ID_ANY, u"关\tCtrl+K", "", wx.ITEM_RADIO)
		self.Bind(wx.EVT_MENU, self.OnWordExplain, self.frame_menubar.explain_off)
		self.frame_menubar.explain_auto = wxglade_tmp_menu_sub.Append(wx.ID_ANY, u"自动\tCtrl+L", "", wx.ITEM_RADIO)
		self.Bind(wx.EVT_MENU, self.OnWordExplain, self.frame_menubar.explain_auto)
		wxglade_tmp_menu.Append(wx.ID_ANY, u"逐字解释(&G)", wxglade_tmp_menu_sub, "")
		item = wxglade_tmp_menu.Append(wx.ID_ANY, u"首选项(&P)\tCtrl+P", "")
		self.Bind(wx.EVT_MENU, self.OnPreferences, item)
		self.frame_menubar.Append(wxglade_tmp_menu, u"打字(&I)")
		wxglade_tmp_menu = wx.Menu()
		item = wxglade_tmp_menu.Append(wx.ID_ANY, u"查汉字(&D)\tCtrl+D", "")
		self.Bind(wx.EVT_MENU, self.OnHanziDialog, item)
		item = wxglade_tmp_menu.Append(wx.ID_ANY, u"查五笔(&F)\tCtrl+F", "")
		self.Bind(wx.EVT_MENU, self.OnWubiDialog, item)
		self.frame_menubar.Append(wxglade_tmp_menu, u"工具(&T)")
		self.SetMenuBar(self.frame_menubar)
		# Menu Bar end

		self.frame_statusbar = self.CreateStatusBar(3)
		self.frame_statusbar.SetStatusWidths([-1, -1, -1])
		# statusbar fields
		frame_statusbar_fields = [u"已完成...", u"剩余...", u"共..."]
		for i in range(len(frame_statusbar_fields)):
			self.frame_statusbar.SetStatusText(frame_statusbar_fields[i], i)

		self.panel_1 = wx.Panel(self, wx.ID_ANY)

		sizer_1_h = wx.BoxSizer(wx.HORIZONTAL)

		sizer_2_v = wx.BoxSizer(wx.VERTICAL)
		sizer_1_h.Add(sizer_2_v, 1, wx.ALL | wx.EXPAND, 3)

		label_2 = wx.StaticText(self.panel_1, wx.ID_ANY, u"练习方案(&E)")
		sizer_2_v.Add(label_2, 0, 0, 0)

		self.tree = wx.TreeCtrl(self.panel_1, wx.ID_ANY, style=wx.TR_HAS_BUTTONS | wx.TR_HIDE_ROOT)
		sizer_2_v.Add(self.tree, 1, wx.EXPAND, 0)

		self.label_notification = wx.StaticText(self.panel_1, wx.ID_ANY, "")
		self.label_notification.Hide()
		sizer_2_v.Add(self.label_notification, 0, 0, 0)

		sizer_3_v = wx.BoxSizer(wx.VERTICAL)
		sizer_1_h.Add(sizer_3_v, 2, wx.ALL | wx.EXPAND, 3)

		sizer_4_h = wx.BoxSizer(wx.HORIZONTAL)
		sizer_3_v.Add(sizer_4_h, 1, wx.ALL | wx.EXPAND, 2)

		self.button_start = wx.Button(self.panel_1, wx.ID_ANY, u"开始(&S)")
		sizer_4_h.Add(self.button_start, 1, wx.ALL, 3)

		sizer_6_h = wx.BoxSizer(wx.HORIZONTAL)
		sizer_4_h.Add(sizer_6_h, 1, wx.EXPAND, 0)

		self.label_display = wx.StaticText(self.panel_1, wx.ID_ANY, u"输入")
		sizer_6_h.Add(self.label_display, 1, 0, 0)

		self.tc_typing = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
		sizer_6_h.Add(self.tc_typing, 1, 0, 0)

		sizer_5_v = wx.BoxSizer(wx.VERTICAL)
		sizer_3_v.Add(sizer_5_v, 5, wx.EXPAND, 0)

		label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, u"已输入")
		sizer_5_v.Add(label_1, 0, 0, 0)

		self.tc_show = wx.TextCtrl(self.panel_1, wx.ID_ANY, "", style=wx.TE_MULTILINE | wx.TE_READONLY)
		self.tc_show.SetMinSize((300, 300))
		sizer_5_v.Add(self.tc_show, 1, 0, 0)

		self.panel_1.SetSizer(sizer_1_h)

		self.Layout()
		self.Centre()

		self.Bind(wx.EVT_BUTTON, self.OnStartBTN, self.button_start)
		self.Bind(wx.EVT_TEXT, self.OnTypingText, self.tc_typing)
		# end wxGlade

	def OnWechat(self, event):  # wxGlade: TypingMaster.<event_handler>
		print("Event handler 'OnWechat' not implemented!")
		event.Skip()

	def OnAlipay(self, event):  # wxGlade: TypingMaster.<event_handler>
		print("Event handler 'OnAlipay' not implemented!")
		event.Skip()

	def OnQQGroupNumber(self, event):  # wxGlade: TypingMaster.<event_handler>
		print("Event handler 'OnQQGroupNumber' not implemented!")
		event.Skip()

	def OnQQQRCode(self, event):  # wxGlade: TypingMaster.<event_handler>
		print("Event handler 'OnQQQRCode' not implemented!")
		event.Skip()

	def OnQQLink(self, event):  # wxGlade: TypingMaster.<event_handler>
		print("Event handler 'OnQQLink' not implemented!")
		event.Skip()

	def OnExit(self, event):  # wxGlade: TypingMaster.<event_handler>
		print("Event handler 'OnExit' not implemented!")
		event.Skip()

	def OnExtremeSpeed(self, event):  # wxGlade: TypingMaster.<event_handler>
		print("Event handler 'OnExtremeSpeed' not implemented!")
		event.Skip()

	def OnStatisticReport(self, event):  # wxGlade: TypingMaster.<event_handler>
		print("Event handler 'OnStatisticReport' not implemented!")
		event.Skip()

	def OnWordExplain(self, event):  # wxGlade: TypingMaster.<event_handler>
		print("Event handler 'OnWordExplain' not implemented!")
		event.Skip()

	def OnPreferences(self, event):  # wxGlade: TypingMaster.<event_handler>
		print("Event handler 'OnPreferences' not implemented!")
		event.Skip()

	def OnHanziDialog(self, event):  # wxGlade: TypingMaster.<event_handler>
		print("Event handler 'OnHanziDialog' not implemented!")
		event.Skip()

	def OnWubiDialog(self, event):  # wxGlade: TypingMaster.<event_handler>
		print("Event handler 'OnWubiDialog' not implemented!")
		event.Skip()

	def OnStartBTN(self, event):  # wxGlade: TypingMaster.<event_handler>
		print("Event handler 'OnStartBTN' not implemented!")
		event.Skip()

	def OnTypingText(self, event):  # wxGlade: TypingMaster.<event_handler>
		print("Event handler 'OnTypingText' not implemented!")
		event.Skip()

# end of class TypingMaster

class StatisticDialog(wx.Dialog):
	def __init__(self, *args, **kwds):
		# begin wxGlade: StatisticDialog.__init__
		kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE
		wx.Dialog.__init__(self, *args, **kwds)
		self.SetTitle(u"打字统计")

		sizer_1 = wx.BoxSizer(wx.VERTICAL)

		self.tc_display = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.TE_MULTILINE | wx.TE_READONLY)
		self.tc_display.SetMinSize((600, 500))
		sizer_1.Add(self.tc_display, 0, 0, 0)

		sizer_2 = wx.StdDialogButtonSizer()
		sizer_1.Add(sizer_2, 0, wx.ALIGN_RIGHT | wx.ALL, 4)

		self.button_OK = wx.Button(self, wx.ID_OK, "")
		self.button_OK.SetDefault()
		sizer_2.AddButton(self.button_OK)

		self.button_CANCEL = wx.Button(self, wx.ID_CANCEL, "")
		sizer_2.AddButton(self.button_CANCEL)

		sizer_2.Realize()

		self.SetSizer(sizer_1)
		sizer_1.Fit(self)
		sizer_1.SetSizeHints(self)

		self.SetAffirmativeId(self.button_OK.GetId())
		self.SetEscapeId(self.button_CANCEL.GetId())

		self.Layout()
		self.Centre()
		# end wxGlade

# end of class StatisticDialog

class SpeedDialog(wx.Dialog):
	def __init__(self, *args, **kwds):
		# begin wxGlade: SpeedDialog.__init__
		kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE
		wx.Dialog.__init__(self, *args, **kwds)
		self.SetSize((750, 680))
		self.SetTitle(u"极限测速")

		sizer_1 = wx.BoxSizer(wx.VERTICAL)

		self.tc_typing = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.TE_MULTILINE)
		self.tc_typing.SetMinSize((750, 600))
		sizer_1.Add(self.tc_typing, 0, 0, 0)

		sizer_2 = wx.StdDialogButtonSizer()
		sizer_1.Add(sizer_2, 0, wx.ALIGN_RIGHT | wx.ALL, 4)

		self.btn_start = wx.Button(self, wx.ID_ANY, u"开始(&S)")
		sizer_2.Add(self.btn_start, 0, 0, 0)

		self.btn_close = wx.Button(self, wx.ID_ANY, u"关闭(&X)")
		sizer_2.Add(self.btn_close, 0, 0, 0)

		sizer_2.Realize()

		self.SetSizer(sizer_1)
		sizer_1.SetSizeHints(self)

		self.Layout()
		self.Centre()

		self.Bind(wx.EVT_BUTTON, self.OnStart, self.btn_start)
		self.Bind(wx.EVT_BUTTON, self.OnClose, self.btn_close)
		# end wxGlade

	def OnStart(self, event):  # wxGlade: SpeedDialog.<event_handler>
		print("Event handler 'OnStart' not implemented!")
		event.Skip()

	def OnClose(self, event):  # wxGlade: SpeedDialog.<event_handler>
		print("Event handler 'OnClose' not implemented!")
		event.Skip()

# end of class SpeedDialog

class PreferencesDialog(wx.Dialog):
	def __init__(self, *args, **kwds):
		# begin wxGlade: PreferencesDialog.__init__
		kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE
		wx.Dialog.__init__(self, *args, **kwds)
		self.SetSize((700, 560))
		self.SetTitle(u"首选项")

		sizer_1 = wx.BoxSizer(wx.VERTICAL)

		sizer_h = wx.BoxSizer(wx.HORIZONTAL)
		sizer_1.Add(sizer_h, 1, wx.EXPAND, 0)

		sizer_4_v = wx.BoxSizer(wx.VERTICAL)
		sizer_h.Add(sizer_4_v, 1, wx.EXPAND, 0)

		label_1 = wx.StaticText(self, wx.ID_ANY, u"思考 时间（秒）(&T)")
		sizer_4_v.Add(label_1, 0, 0, 0)

		self.combo_box_time = wx.ComboBox(self, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN | wx.CB_READONLY)
		sizer_4_v.Add(self.combo_box_time, 0, 0, 0)

		sizer_3_h = wx.BoxSizer(wx.HORIZONTAL)
		sizer_1.Add(sizer_3_h, 1, wx.ALL | wx.EXPAND, 2)

		sizer_5_v = wx.BoxSizer(wx.VERTICAL)
		sizer_3_h.Add(sizer_5_v, 1, wx.EXPAND, 0)

		label_2 = wx.StaticText(self, wx.ID_ANY, u"提示方式(&S)")
		sizer_5_v.Add(label_2, 0, 0, 0)

		self.choice_speak_mode = wx.Choice(self, wx.ID_ANY, choices=[u"读屏", u"内置语音库", u"争渡API", "NVDA API"])
		self.choice_speak_mode.SetSelection(0)
		sizer_5_v.Add(self.choice_speak_mode, 0, 0, 0)

		sizer_6_v = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, u"语音"), wx.VERTICAL)
		sizer_3_h.Add(sizer_6_v, 1, wx.BOTTOM | wx.EXPAND | wx.TOP, 3)

		self.choice_voice = wx.Choice(self, wx.ID_ANY, choices=[])
		sizer_6_v.Add(self.choice_voice, 0, 0, 0)

		sizer_5 = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, u"音量"), wx.VERTICAL)
		sizer_3_h.Add(sizer_5, 1, wx.BOTTOM | wx.EXPAND | wx.TOP, 3)

		self.slider_volume = wx.Slider(self, wx.ID_ANY, 90, 0, 100)
		sizer_5.Add(self.slider_volume, 0, wx.EXPAND, 0)

		sizer_6 = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, u"语速"), wx.VERTICAL)
		sizer_3_h.Add(sizer_6, 1, wx.BOTTOM | wx.EXPAND | wx.TOP, 3)

		self.slider_rate = wx.Slider(self, wx.ID_ANY, 50, 0, 100)
		sizer_6.Add(self.slider_rate, 0, wx.EXPAND, 0)

		sizer_7 = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, u"音调"), wx.VERTICAL)
		sizer_3_h.Add(sizer_7, 1, wx.BOTTOM | wx.EXPAND | wx.TOP, 3)

		self.slider_pitch = wx.Slider(self, wx.ID_ANY, 50, 0, 100)
		sizer_7.Add(self.slider_pitch, 0, wx.EXPAND, 0)

		self.btn_listen_ = wx.Button(self, wx.ID_ANY, u"试听(&P)")
		sizer_3_h.Add(self.btn_listen_, 0, 0, 0)

		sizer_2 = wx.StdDialogButtonSizer()
		sizer_1.Add(sizer_2, 0, wx.ALIGN_RIGHT | wx.ALL, 4)

		self.button_OK = wx.Button(self, wx.ID_OK, "")
		self.button_OK.SetDefault()
		sizer_2.AddButton(self.button_OK)

		self.button_CANCEL = wx.Button(self, wx.ID_CANCEL, "")
		sizer_2.AddButton(self.button_CANCEL)

		sizer_2.Realize()

		self.SetSizer(sizer_1)
		sizer_1.SetSizeHints(self)

		self.SetAffirmativeId(self.button_OK.GetId())
		self.SetEscapeId(self.button_CANCEL.GetId())

		self.Layout()
		self.Centre()

		self.Bind(wx.EVT_CHOICE, self.OnSpeakMode, self.choice_speak_mode)
		self.Bind(wx.EVT_BUTTON, self.OnListen, self.btn_listen_)
		# end wxGlade

	def OnSpeakMode(self, event):  # wxGlade: PreferencesDialog.<event_handler>
		print("Event handler 'OnSpeakMode' not implemented!")
		event.Skip()

	def OnListen(self, event):  # wxGlade: PreferencesDialog.<event_handler>
		print("Event handler 'OnListen' not implemented!")
		event.Skip()

# end of class PreferencesDialog

class EditDialog(wx.Dialog):
	def __init__(self, *args, **kwds):
		# begin wxGlade: EditDialog.__init__
		kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE
		wx.Dialog.__init__(self, *args, **kwds)
		self.SetSize((400, 800))

		sizer_1 = wx.BoxSizer(wx.VERTICAL)

		sizer_3 = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, u"方案名称"), wx.HORIZONTAL)
		sizer_1.Add(sizer_3, 1, wx.EXPAND, 0)

		self.combo_box_name = wx.ComboBox(self, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN)
		sizer_3.Add(self.combo_box_name, 0, 0, 0)

		sizer_4 = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, u"内容"), wx.HORIZONTAL)
		sizer_1.Add(sizer_4, 1, wx.EXPAND, 0)

		self.tc_content = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.TE_MULTILINE)
		sizer_4.Add(self.tc_content, 0, 0, 0)

		sizer_2 = wx.StdDialogButtonSizer()
		sizer_1.Add(sizer_2, 0, wx.ALIGN_RIGHT | wx.ALL, 4)

		self.button_OK = wx.Button(self, wx.ID_OK, "")
		self.button_OK.SetDefault()
		sizer_2.AddButton(self.button_OK)

		self.button_CANCEL = wx.Button(self, wx.ID_CANCEL, "")
		sizer_2.AddButton(self.button_CANCEL)

		sizer_2.Realize()

		self.SetSizer(sizer_1)
		sizer_1.SetSizeHints(self)

		self.SetAffirmativeId(self.button_OK.GetId())
		self.SetEscapeId(self.button_CANCEL.GetId())

		self.Layout()
		self.Centre()

		self.Bind(wx.EVT_BUTTON, self.OnAddIncorrectBTN, self.button_OK)
		# end wxGlade

	def OnAddIncorrectBTN(self, event):  # wxGlade: EditDialog.<event_handler>
		print("Event handler 'OnAddIncorrectBTN' not implemented!")
		event.Skip()

# end of class EditDialog

class WuBiDialog(wx.Dialog):
	def __init__(self, *args, **kwds):
		# begin wxGlade: WuBiDialog.__init__
		kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE
		wx.Dialog.__init__(self, *args, **kwds)
		self.SetTitle(u"五笔编码查询")

		sizer_1 = wx.BoxSizer(wx.VERTICAL)

		sizer_h = wx.BoxSizer(wx.HORIZONTAL)
		sizer_1.Add(sizer_h, 1, wx.EXPAND, 0)

		sizer_3 = wx.BoxSizer(wx.VERTICAL)
		sizer_h.Add(sizer_3, 1, wx.EXPAND, 0)

		label_single = wx.StaticText(self, wx.ID_ANY, u"单字(&G)")
		sizer_3.Add(label_single, 0, 0, 0)

		self.choice_single = wx.Choice(self, wx.ID_ANY, choices=[u"最短的编码", u"最长的编码", u"所有可能的编码"])
		self.choice_single.SetSelection(0)
		sizer_3.Add(self.choice_single, 0, 0, 0)

		sizer_4 = wx.BoxSizer(wx.VERTICAL)
		sizer_h.Add(sizer_4, 1, wx.EXPAND, 0)

		label_3 = wx.StaticText(self, wx.ID_ANY, u"多字(&M)")
		sizer_4.Add(label_3, 0, 0, 0)

		self.choice_multi = wx.Choice(self, wx.ID_ANY, choices=[u"做为一个整体", u"分别查询每个字"])
		self.choice_multi.SetSelection(0)
		sizer_4.Add(self.choice_multi, 0, 0, 0)

		sizer_1_h = wx.BoxSizer(wx.HORIZONTAL)
		sizer_1.Add(sizer_1_h, 1, wx.EXPAND, 0)

		label_1 = wx.StaticText(self, wx.ID_ANY, u"输入(&I)")
		sizer_1_h.Add(label_1, 0, 0, 0)

		self.combo_box_input = wx.ComboBox(self, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN | wx.TE_PROCESS_ENTER)
		self.combo_box_input.SetFocus()
		sizer_1_h.Add(self.combo_box_input, 0, 0, 0)

		self.btn_search = wx.Button(self, wx.ID_ANY, u"查询(&S)")
		sizer_1_h.Add(self.btn_search, 0, 0, 0)

		sizer_2_h = wx.BoxSizer(wx.HORIZONTAL)
		sizer_1.Add(sizer_2_h, 1, wx.EXPAND, 0)

		label_2 = wx.StaticText(self, wx.ID_ANY, u"查询结果")
		sizer_2_h.Add(label_2, 0, 0, 0)

		self.tc_result = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.TE_MULTILINE | wx.TE_READONLY)
		sizer_2_h.Add(self.tc_result, 0, 0, 0)

		sizer_2 = wx.StdDialogButtonSizer()
		sizer_1.Add(sizer_2, 0, wx.ALIGN_RIGHT | wx.ALL, 4)

		self.button_CLOSE = wx.Button(self, wx.ID_CLOSE, "")
		sizer_2.AddButton(self.button_CLOSE)

		sizer_2.Realize()

		self.SetSizer(sizer_1)
		sizer_1.Fit(self)
		sizer_1.SetSizeHints(self)

		self.SetEscapeId(self.button_CLOSE.GetId())

		self.Layout()

		self.Bind(wx.EVT_TEXT_ENTER, self.OnSearchCB, self.combo_box_input)
		self.Bind(wx.EVT_BUTTON, self.OnSearchBTN, self.btn_search)
		# end wxGlade

	def OnSearchCB(self, event):  # wxGlade: WuBiDialog.<event_handler>
		print("Event handler 'OnSearchCB' not implemented!")
		event.Skip()

	def OnSearchBTN(self, event):  # wxGlade: WuBiDialog.<event_handler>
		print("Event handler 'OnSearchBTN' not implemented!")
		event.Skip()

# end of class WuBiDialog

class HanZiDialog(wx.Dialog):
	def __init__(self, *args, **kwds):
		# begin wxGlade: HanZiDialog.__init__
		kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE
		wx.Dialog.__init__(self, *args, **kwds)
		self.SetTitle(u"汉字查询")

		sizer_v = wx.BoxSizer(wx.VERTICAL)

		sizer_1h = wx.BoxSizer(wx.HORIZONTAL)
		sizer_v.Add(sizer_1h, 1, wx.EXPAND, 0)

		sizer_4 = wx.BoxSizer(wx.VERTICAL)
		sizer_1h.Add(sizer_4, 1, wx.EXPAND, 0)

		label_source = wx.StaticText(self, wx.ID_ANY, u"来源(&C)")
		sizer_4.Add(label_source, 0, 0, 0)

		self.combo_box_source = wx.ComboBox(self, wx.ID_ANY, choices=[u"汉字", u"本地", u"汉语"], style=wx.CB_DROPDOWN | wx.CB_READONLY)
		self.combo_box_source.SetSelection(0)
		sizer_4.Add(self.combo_box_source, 0, 0, 0)

		sizer_5 = wx.BoxSizer(wx.VERTICAL)
		sizer_1h.Add(sizer_5, 1, wx.EXPAND, 0)

		label_input = wx.StaticText(self, wx.ID_ANY, u"输入汉字(&I)")
		sizer_5.Add(label_input, 0, 0, 0)

		self.combo_box_input = wx.ComboBox(self, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN | wx.TE_PROCESS_ENTER)
		self.combo_box_input.SetFocus()
		sizer_5.Add(self.combo_box_input, 0, 0, 0)

		sizer_6 = wx.BoxSizer(wx.VERTICAL)
		sizer_1h.Add(sizer_6, 1, wx.EXPAND, 0)

		self.btn_search = wx.Button(self, wx.ID_ANY, u"查询(&S)")
		sizer_6.Add(self.btn_search, 0, 0, 0)

		sizer_2h = wx.BoxSizer(wx.HORIZONTAL)
		sizer_v.Add(sizer_2h, 1, wx.EXPAND, 0)

		sizer_7 = wx.BoxSizer(wx.VERTICAL)
		sizer_2h.Add(sizer_7, 1, wx.EXPAND, 0)

		label_3 = wx.StaticText(self, wx.ID_ANY, u"查询结果")
		sizer_7.Add(label_3, 0, 0, 0)

		self.tc_result = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.TE_MULTILINE | wx.TE_READONLY)
		self.tc_result.SetMinSize((600, 410))
		sizer_7.Add(self.tc_result, 0, 0, 0)

		sizer_2 = wx.StdDialogButtonSizer()
		sizer_v.Add(sizer_2, 0, wx.ALIGN_RIGHT | wx.ALL, 4)

		self.button_CLOSE = wx.Button(self, wx.ID_CLOSE, "")
		sizer_2.AddButton(self.button_CLOSE)

		sizer_2.Realize()

		self.SetSizer(sizer_v)
		sizer_v.Fit(self)
		sizer_v.SetSizeHints(self)

		self.SetEscapeId(self.button_CLOSE.GetId())

		self.Layout()

		self.Bind(wx.EVT_TEXT_ENTER, self.OnSearchCB, self.combo_box_input)
		self.Bind(wx.EVT_BUTTON, self.OnSearchBTN, self.btn_search)
		# end wxGlade

	def OnSearchCB(self, event):  # wxGlade: HanZiDialog.<event_handler>
		print("Event handler 'OnSearchCB' not implemented!")
		event.Skip()

	def OnSearchBTN(self, event):  # wxGlade: HanZiDialog.<event_handler>
		print("Event handler 'OnSearchBTN' not implemented!")
		event.Skip()

# end of class HanZiDialog

class MyApp(wx.App):
	def OnInit(self):
		self.frame = TypingMaster(None, wx.ID_ANY, "")
		self.SetTopWindow(self.frame)
		self.frame.Show()
		return True

# end of class MyApp

if __name__ == "__main__":
	app = MyApp(0)
	app.MainLoop()
